### ISSUE TITLE
Only the bundled version works

### ISSUE THREAD

**Issue by LikeyX** [mcgrizzz/NVCP_Toggle#6]
Only the bundled Version works actually. 
On all other Versions the WindowsDisplayAPI from falahati is missing.

**Comment by mcgrizzz** [comment]
This is because there a very few compiled releases here: https://github.com/falahati/WindowsDisplayAPI/releases 

When writing this, I had to compile from the repository for certain functionality.

It looks like some of that functionality has been changed now. However, there are no new releases from falahati. 

Since I do not have time to rework this project at the moment. I'll remove the non-bundled package from the release.

**Comment by LikeyX** [comment]
Ahye i tried alot the last hours. It's because its limitied to .net 4.5 or 2.0 and for example VS 2022 doesnt support it without workarounds. 
I close it here and thanks for your answer!

**Comment by LikeyX** [comment]
done
